// <auto-generated />
using System;
using CargoParcelTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoParcelTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231122323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CargoParcelTracker.Models.CargoParcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ApiGravity")
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationPortId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LoadingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginPortId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TankerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPortId");

                    b.HasIndex("OriginPortId");

                    b.HasIndex("TankerId");

                    b.ToTable("CargoParcels");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Tanker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImoNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tankers");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.CargoParcel", b =>
                {
                    b.HasOne("CargoParcelTracker.Models.Port", "DestinationPort")
                        .WithMany()
                        .HasForeignKey("DestinationPortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CargoParcelTracker.Models.Port", "OriginPort")
                        .WithMany()
                        .HasForeignKey("OriginPortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CargoParcelTracker.Models.Tanker", "Tanker")
                        .WithMany("CargoParcels")
                        .HasForeignKey("TankerId");

                    b.Navigation("DestinationPort");

                    b.Navigation("OriginPort");

                    b.Navigation("Tanker");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Tanker", b =>
                {
                    b.Navigation("CargoParcels");
                });
#pragma warning restore 612, 618
        }
    }
}
