// <auto-generated />
using System;
using CargoParcelTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoParcelTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231122921_AddDomainModels")]
    partial class AddDomainModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CargoParcelTracker.Models.CargoParcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrudeGrade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DischargePort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LaycanEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LaycanStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadingPort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParcelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityBbls")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TankerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TankerId");

                    b.ToTable("CargoParcels");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Tanker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImoNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tankers");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dwt")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImoNumber")
                        .IsUnique();

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.VoyageAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DemurrageRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DischargeDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreightRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VesselId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId");

                    b.HasIndex("VesselId");

                    b.ToTable("VoyageAllocations");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.CargoParcel", b =>
                {
                    b.HasOne("CargoParcelTracker.Models.Tanker", null)
                        .WithMany("CargoParcels")
                        .HasForeignKey("TankerId");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.VoyageAllocation", b =>
                {
                    b.HasOne("CargoParcelTracker.Models.CargoParcel", "CargoParcel")
                        .WithMany("VoyageAllocations")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoParcelTracker.Models.Vessel", "Vessel")
                        .WithMany("VoyageAllocations")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CargoParcel");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.CargoParcel", b =>
                {
                    b.Navigation("VoyageAllocations");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Tanker", b =>
                {
                    b.Navigation("CargoParcels");
                });

            modelBuilder.Entity("CargoParcelTracker.Models.Vessel", b =>
                {
                    b.Navigation("VoyageAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
